import 'dart:ui';

import 'package:flutter/material.dart';

const colorPrimary = Color(0xffE40045);
const colorPrimaryDark = Color(0xff554625);
const gradient1 = Color(0xFF545C68);
const bgGray = Color(0xFFF2F2F2);
const textfieldGrey = Color(0xFFD9D9D9);
const lineColor = Color(0xFFCDCDCD);
const lightprimaryColor = Color(0xFFEDE7D1);
const lightgreen = Color(0xFFBCFFCB);
const grey = Color(0xff4F4F4F);
const greylight = Color(0xfff4f4f4);
const grey1 = Color(0xffBDBDBD);
const scaffoldBg = Color(0xfff5f5f5);
const grey2 = Color(0xffE0E0E0);
const white = Color(0xffFFFFFF);
const creamBorder = Color(0xffF3E7C8);
const couponBackground = Color(0xfff3f3f3);
const textColor = Color(0xff333333);
const textColorlight = Color(0xff5A5A5A);
const lightCouponBackground = Color(0xffFEF2F6);
const logoBackground = Color(0xffF8E0AB);
const lightGrey = Color(0xffAFAFAF);
const blue = Color(0xff1568CB);
const orange = Color(0xffE57B1C);
const green = Color(0xff219653);
const scaffoldBackground = Color(0xfffefefe);
const yellow = Color(0xffF8DFAA);
