// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4o2Hv00_HmA1PWM-zhB2qI9DHMp1IU5Y',
    appId: '1:1032882392426:web:8dbf26907cb0b0fc5c6913',
    messagingSenderId: '1032882392426',
    projectId: 'sheegr-a06b6',
    authDomain: 'sheegr-a06b6.firebaseapp.com',
    storageBucket: 'sheegr-a06b6.appspot.com',
    measurementId: 'G-CSHF23Q6LN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5O9--meMc7cceDgKoQLM8jWMhlsa2OWw',
    appId: '1:1032882392426:android:600648d4815228635c6913',
    messagingSenderId: '1032882392426',
    projectId: 'sheegr-a06b6',
    storageBucket: 'sheegr-a06b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM3xFt66q5yIkY3mPdkthxOHNmaGEUWy0',
    appId: '1:1032882392426:ios:5943467f1e15c43c5c6913',
    messagingSenderId: '1032882392426',
    projectId: 'sheegr-a06b6',
    storageBucket: 'sheegr-a06b6.appspot.com',
    iosClientId: '1032882392426-dntnen41v5khdf396j159rqa5me6kiqk.apps.googleusercontent.com',
    iosBundleId: 'com.example.sheegr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM3xFt66q5yIkY3mPdkthxOHNmaGEUWy0',
    appId: '1:1032882392426:ios:6a436d247e85b2895c6913',
    messagingSenderId: '1032882392426',
    projectId: 'sheegr-a06b6',
    storageBucket: 'sheegr-a06b6.appspot.com',
    iosClientId: '1032882392426-qhr827m3pf6s16lphftt91dte35e26v5.apps.googleusercontent.com',
    iosBundleId: 'com.example.sheegr.RunnerTests',
  );
}
