// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOLnqGc0s_nq_oGTIL3h2SDwIH9DlF1J8',
    appId: '1:140075343149:web:561a48ebbdba348da6c7a4',
    messagingSenderId: '140075343149',
    projectId: 'sheegr-1837d',
    authDomain: 'sheegr-1837d.firebaseapp.com',
    storageBucket: 'sheegr-1837d.appspot.com',
    measurementId: 'G-BFJBYM8JMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC4f2kRv40TeBRKZyrCRredUvYAjsh6q0',
    appId: '1:140075343149:android:a0f117bb61450b7aa6c7a4',
    messagingSenderId: '140075343149',
    projectId: 'sheegr-1837d',
    storageBucket: 'sheegr-1837d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFpMqkfQQJNvJsWBq44GBr3glQLOuyi64',
    appId: '1:140075343149:ios:182fcf9b6d72cb46a6c7a4',
    messagingSenderId: '140075343149',
    projectId: 'sheegr-1837d',
    storageBucket: 'sheegr-1837d.appspot.com',
    androidClientId: '140075343149-ivhe0ueamqdc21gk5mjklobj34m34p1o.apps.googleusercontent.com',
    iosClientId: '140075343149-109h0ud06tdp5167s21cm8m9mvt92k0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.sheegr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFpMqkfQQJNvJsWBq44GBr3glQLOuyi64',
    appId: '1:140075343149:ios:9ccdb1366dbc99bea6c7a4',
    messagingSenderId: '140075343149',
    projectId: 'sheegr-1837d',
    storageBucket: 'sheegr-1837d.appspot.com',
    androidClientId: '140075343149-ivhe0ueamqdc21gk5mjklobj34m34p1o.apps.googleusercontent.com',
    iosClientId: '140075343149-nl2cp0nu6u3fn185hfaq5sspt7mvk42k.apps.googleusercontent.com',
    iosBundleId: 'com.example.sheegr.RunnerTests',
  );
}
